### ISSUE TITLE
finir intro

### ISSUE THREAD

**Issue by urosselet** [HE-Arc-ODI/git-workflow-workshop-for-two#1]
parallèliser les instructions jusqu'au point "Splitting the work"
ensuite, vérifier que la fin de l'exercice est cohérente.

**Comment by dylanmontandon** [comment]
Hello, j'ai bien fait jusqu'au point "splitting the work" mais je n'ai malheureusement pas eu le temps de bien vérifier que la fin de l'exercice soit cohérent (certaines images n'ont pas été modifiées par exemple) je ferai la fin demain a moins que tu veuilles le faire toi ? Bonne soirée !

**Comment by urosselet** [comment]
Hello!
OK tu peux le faire toi ! J'ai zéro temps ajd. Merci !

Le 25 sept. 2018 22:13, Dylan Montandon <notifications@github.com> a écrit :

Hello, j'ai bien fait jusqu'au point "splitting the work" mais je n'ai malheureusement pas eu le temps de bien vérifier que la fin de l'exercice soit cohérent (certaines images n'ont pas été modifiées par exemple) je ferai la fin demain a moins que tu veuilles le faire toi ? Bonne soirée !

**Comment by dylanmontandon** [comment]
Exercice terminé, tu peux regarder si ça correspond à ce que tu veux!
